"""Add SkinEvaluation model

Revision ID: 42e8901e625d
Revises: 16e5f16ce898
Create Date: 2026-10-07 03:34:15.045828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42e8901e625d'
down_revision = '16e5f16ce898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skin_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('requires_professional_attention', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skin_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skin_evaluations_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skin_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skin_evaluations_user_id'))

    op.drop_table('skin_evaluations')
    # ### end Alembic commands ###
